#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

# Ensure all environment files exist
touch ldap.env
touch smarthost.env
touch config.env

# Enable Matrix services
systemctl --user enable dex.service
systemctl --user enable synapse.service  
systemctl --user enable element-web.service
systemctl --user enable matrix.service

# Restart Matrix services
systemctl --user restart dex.service
systemctl --user restart synapse.service  
systemctl --user restart element-web.service
systemctl --user restart matrix.service