#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

# Ensure LDAP and SMTP environment files exist
touch ldap.env
touch smarthost.env

# Start and enable Matrix services
systemctl --user enable --now dex.service
systemctl --user enable --now synapse.service  
systemctl --user enable --now element-web.service
systemctl --user enable --now matrix.service