issuer: https://${SYNAPSE_DOMAIN_NAME}/dex

storage:
  type: sqlite3
  config:
    file: /var/lib/dex/dex.db

web:
  http: 0.0.0.0:${DEX_PORT}

staticClients:
  - id: synapse
    redirectURIs:
      - 'https://${SYNAPSE_DOMAIN_NAME}/_synapse/client/oidc/callback'
    name: 'Synapse'
    secret: synapse-secret

connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: ${DEX_LDAP_HOST}:${DEX_LDAP_PORT}
      insecureNoSSL: true
      bindDN: ${DEX_LDAP_BIND_DN}
      bindPW: ${DEX_LDAP_BIND_PASSWORD}
      usernamePrompt: Username
      userSearch:
        baseDN: ${DEX_LDAP_BASE_DN}
        filter: ${DEX_LDAP_USER_FILTER}
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: ${DEX_LDAP_BASE_DN}
        filter: "(objectClass=groupOfNames)"
        userMatchers:
          - userAttr: DN
            groupAttr: member
        nameAttr: cn

oauth2:
  skipApprovalScreen: true